# Generated by Django 4.2.29 on 2026-03-10 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_lang', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese (Simplified)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('nl', 'Dutch'), ('pl', 'Polish'), ('hi', 'Hindi'), ('fa', 'Persian'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('target_lang', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese (Simplified)'), ('ja', 'Japanese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('nl', 'Dutch'), ('pl', 'Polish'), ('hi', 'Hindi'), ('fa', 'Persian'), ('ur', 'Urdu')], default='ar', max_length=5)),
                ('category', models.CharField(choices=[('legal', 'Legal'), ('medical', 'Medical'), ('technical', 'Technical'), ('literary', 'Literary'), ('business', 'Business'), ('marketing', 'Marketing'), ('academic', 'Academic'), ('subtitles', 'Subtitles / Captions'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='community/')),
                ('original_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='translators.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
