# Generated by Django 4.2.29 on 2026-03-10 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('text', 'Text Translation'), ('file', 'File Translation'), ('video_url', 'Video URL'), ('video_upload', 'Video Upload')], default='text', max_length=20)),
                ('source_lang', models.CharField(default='auto', max_length=5)),
                ('target_lang', models.CharField(default='ar', max_length=5)),
                ('original_text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
