# Generated by Django 4.2.29 on 2026-03-10 07:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationjob',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
